### ISSUE TITLE
Explain and discuss the options of ad-hoc and long-lasting client attestations

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#10]
Options on requesting/generating the client/wallet attestation ad-hoc or in advance have been discussed and there are pros and cons for both sides. Is a short explanation of this suited for the RFC?

**Comment by tplooker** [comment]
Suggest closing as we shouldn't comment on attestation token lifetimes anymore then OAuth2 comments on expected AT lifetimes, its at the discretion of the implementation which is often highly deployment specific.
