### ISSUE TITLE
Why not just use the same client attestation JWT? That would not require any client instance identification and is also not a privacy issue.

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#12]
Why not just use the same client attestation JWT? That would not require any client instance identification and is also not a privacy issue. 

urn:ietf:params:oauth:client-assertion-type:jwt-key-attestation -> urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation

_Originally posted by @tlodderstedt in https://github.com/vcstuff/draft-looker-oauth-attested-key-based-client-authentication/pull/11#discussion_r1201683953_

**Comment by tplooker** [comment]
Related to #31. The problem with this model is that the refresh token if bound to the client attestation JWT then limits the RT lifetime.
