### ISSUE TITLE
The Entity Attestation Token (EAT)

### ISSUE THREAD

**Issue by peppelinux** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#14]
Is there any considerations about adopting *The Entity Attestation Token (EAT)* [draft-ietf-rats-eat-12](https://datatracker.ietf.org/doc/draft-ietf-rats-eat/12/) for the Attestation JWT?

**Comment by Sakurann** [comment]
I think it is sufficient to add that JWT Claims defined in EAT draft can be put in the attestation JWT?

**Comment by tplooker** [comment]
EAT is a more general purpose token format, however as highlight by @Sakurann implementations are free to make use of claims registered by EAT for their purposes.
