### ISSUE TITLE
Reanme Grant Type to JWT-PoP?

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#17]
Issue raised by Kristina:
I also perceive this draft as a PoP version of urn:ietf:params:oauth:grant-type:jwt-bearer, would it make sense to make that more intuitive and explicit - like urn:ietf:params:oauth:grant-type:jwt-pop? - this can be another issue

_Originally posted by @Sakurann in https://github.com/vcstuff/draft-looker-oauth-attested-key-based-client-authentication/pull/11#pullrequestreview-1451679914_

**Comment by tplooker** [comment]
@Sakurann can you please review the latest terminology in the draft and let us know if you have any issue with it?

**Comment by bc-pi** [comment]
Note that this draft is defining an OAuth client authentication method and *not* a grant type (yes RFC7521 has both but this draft only deals with client auth). So there may well be room for improvement in terminology but it shouldn't be about grant type.

**Comment by paulbastian** [comment]
Pending close if there are no objections
