### ISSUE TITLE
client_assertion_type

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#18]
I perceive this draft as a PoP version of `urn:ietf:params:oauth:grant-type:jwt-bearer`, would it make sense to make that more intuitive and explicit - like `urn:ietf:params:oauth:grant-type:jwt-pop`?

_Originally posted by @Sakurann in https://github.com/vcstuff/draft-looker-oauth-attested-key-based-client-authentication/pull/11#discussion_r1210728395_

**Comment by Sakurann** [comment]
is this duplicate of #17 ?
