### ISSUE TITLE
Send Client Attestation with Authorization Request instead of Token Request

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#27]
There is an idea to send the Client attestation already in Authorization Request or PAR instead of with the Token Request.
I see the following advantages:
 - the client attestation could act as some kind of mobile capability descriptor, thus allowing the Authorization Server(Issuer) to check these before the user performs user authentication, otherwise this could result in poor UX as the user authenticates and the AS realizes only afterwards in Token Request that the level of client attestation is not enough (e.g. wallet can only handle key type xyz or LoA low)

I see the following disadvantage:
- some flows do not require Authorization Request
- the user usually does not give consent before sending Authorization Request

**Comment by tlodderstedt** [comment]
The client attestation can for sure be used to authenticate with PAR. The HAIP already requires that.

**Comment by tplooker** [comment]
The draft just needs to be clarified that this is a general purpose client authentication method that can be used with any interaction with an AS that is requiring or making use of client authentication.
