### ISSUE TITLE
Attestation JWT should be reusable but there's contradictory text 

### ISSUE THREAD

**Issue by bc-pi** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#33]
The Client Attestation JWT seems like a long(er) lived credential that should be reusable so the client instance doesn't have to go get a new one each time (right?*).  But this text [here](https://www.ietf.org/archive/id/draft-looker-oauth-attestation-based-client-auth-00.html#section-4.1.1-2.7) for the Client Attestation JWT has 'The authorization server MAY ensure that JWTs are not replayed by maintaining the set of used "jti" values for the length of time for which the JWT would be considered valid based on the applicable "exp" instant' that suggests the AS might limit them to single use. I think that sentence can just be removed. 

\* right: https://www.ietf.org/archive/id/draft-looker-oauth-attestation-based-client-auth-00.html#name-reuse-of-a-client-attestati

**Comment by tplooker** [comment]
Agreed, need to remove this sentence from step 7 of 4.1.1.
