### ISSUE TITLE
PoP JWT example is not consistent with spec text

### ISSUE THREAD

**Issue by bc-pi** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#34]
The text says jti is required https://www.ietf.org/archive/id/draft-looker-oauth-attestation-based-client-auth-00.html#section-4.1.2-2.3 but the example doesn't have jti https://www.ietf.org/archive/id/draft-looker-oauth-attestation-based-client-auth-00.html#section-4.1.2-3

**Comment by tplooker** [comment]
Duplicate of #37
