### ISSUE TITLE
Sender-Constrained Access Token

### ISSUE THREAD

**Issue by TakahikoKawasaki** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#36]
The specification contains sentences related to sender-constrained acess tokens as follows.

#### In the "1. Introduction" section:
>... The Authorization Server may continue to issue sender-constrained access tokens using DPOP.

#### In the "4.1.1. Client Attestation JWT" section:
> The JWT MUST contain an "cnf" claim conforming RFC7800 that conveys the key to be used for sender constraining tokens issued by the authorization server. The key MUST be expressed using the "jwk" representation.

### Questions

**Q1.** "**Client authentication**" and "**sender-constrained access token**" are different. Is the specification trying to define requirements not only for client authentication but also for sender-constrained access tokens? (FYI: [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html) defines "client authentication" in [Section 2](https://www.rfc-editor.org/rfc/rfc8705.html#section-2) and defines "sender-constrained access token" in [Section 3](https://www.rfc-editor.org/rfc/rfc8705.html#section-3).)

**Q2.** DPOP is mentioned abruptly in the Introduction section but not referenced anywhere else. Is this mention of DPOP merely an example of sender-constrained access tokens, or is it a requirement to bind the Client Instance Key to the access token as if it were specified by DPOP? If it is not a normative requirement, mentioning DPOP would only cause confusion without any benefits. On the contrary, if it is a normative requirement, detailed explanation is needed.

**Q3.** The explanation about the `cnf` claim of the Client Attestation JWT requires authorization server implementations to bind the Client Instance Key to access tokens. Is this normative requirement really intended? If it is intended, how does the client prove that it possesses the private key of the Client Instance Key when accessing protected resource endpoints? DPOP?

**Comment by tplooker** [comment]
The introduction text is fixed by #19

**Comment by tplooker** [comment]
Q2 - We will clarify that any usage of this client authentication method with DPoP is entirely optional. It is as you highlight first and foremost a client authentication method.

Q3 - This is a mistake in the language, thanks for highlighting as above, DPoP is entirely optional.

**Comment by paulbastian** [comment]
The explicit reference to DPoP was removed from the introduction for now.

I would consider adding it to implementation considerations as a recommendation to use DPoP-bound access tokens after client authentication with this spec to achieve a consistent security level

**Comment by tplooker** [comment]
I believe this issue has now been addressed, intend to close soon if there are no objections.

**Comment by tplooker** [comment]
Closing as I believe this now resolved, please reopen if need be.
