### ISSUE TITLE
Change name of the JWT to Client Attestation 

### ISSUE THREAD

**Issue by tlodderstedt** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#6]
I'm struggling with the terminology currently used in this draft. For me, it describes a mechanism to use JWTs to authenticate OAuth clients. 

However, the draft currently designates those JWTs as "Key Attestation" or "attestation key" or "jwt-key-attestation", which sounds like the focus is on attesting something about a certain key to the AS. But that's obviously not the case since, this draft is about client authentication and the key is "just" used to protect the JWT against replay. 

I think the name is confusing and suggest to change it to "Client Attestation".

**Comment by tplooker** [comment]
Agreed, what about "Client Attestation based Client Authentication".

**Comment by tlodderstedt** [comment]
I revisited the title of RFC 7523. What about „Sender-Constrained JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication“?

**Comment by paulbastian** [comment]
@tlodderstedt thats a proposal for the title of the RFC I guess? I'm ok with that..
I propose "Client Attestation JWT" for the actual thing, that we call wallet attestation in our scenario

**Comment by paulbastian** [comment]
Renaming the Client Attestation covered by #11 .
Renaming topic in this issue is about the title?

**Comment by tplooker** [comment]
After thinking about this more I propose "Attestation Based Client Authentication for OAuth 2"

**Comment by tlodderstedt** [comment]
What is the meaning of this title? What does "Attestation based" mean?

**Comment by paulbastian** [comment]
that the Client backend/Attestation Service attests the Client Instance

**Comment by tlodderstedt** [comment]
How is that different from "JWT-based client authentication"? The JWT also contains claims about the client.

**Comment by tplooker** [comment]
Resolved in draft-00
