### ISSUE TITLE
Introduction text

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#7]
The current draft says:

> [[RFC7521](https://vcstuff.github.io/draft-looker-oauth-attested-key-based-client-authentication/draft-looker-oauth-attested-key-based-client-authentication.html#RFC7521)] defines a way for a client to include an assertion in a token request to an authorization server for the purposes of client authentication. This specification extends this mechanism to provide a way for a client instance to authenticate it self with the authorization server through an attested key based authentication scheme.

I don't like the description of a "an attested key based authentication scheme", as key attestations are not always possible and it is more about attesting the wallet and the key being a mechanism.

 I would rather describe the current approach as a
- remote client (instance) attestation scheme
- remote wallet (instance) attestation scheme

**Comment by tplooker** [comment]
Agreed I dont like it particularly either, what about just 

```
[[RFC7521](https://vcstuff.github.io/draft-looker-oauth-attested-key-based-client-authentication/draft-looker-oauth-attested-key-based-client-authentication.html#RFC7521)] defines a way for a client to include an assertion in a token request to an authorization server for the purposes of client authentication. This specification extends this mechanism to provide a way for a client instance to authenticate itself with the authorization server through an attestation based authentication scheme.
```

**Comment by paulbastian** [comment]
I'm fine to close this, see #11

**Comment by paulbastian** [comment]
Rephrased in #39
