### ISSUE TITLE
Make PoP optional

### ISSUE THREAD

**Issue by nikosft** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#75]
I believe there are many existing systems that generate "client attestations" and can benefit from this draft, examples of such client attestations are:

- Github's [oidc token for actions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)
- SPRIFFE [JWT Verifiable Document](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#spiffe-verifiable-identity-document-svid)
- Azure [AD Pod identity](https://azure.github.io/aad-pod-identity/)

However in all these solutions, attestations are not bound to any key.

**Comment by tplooker** [comment]
OpenID and OAuth already have mechanisms for ordinarily signed JWTs as a means of client authentication toward an AS, such as private key jwt and token exchange so I'm unsure how supporting this would be any different to those existing mechanisms?

**Comment by nikosft** [comment]
Yes you are right
