### ISSUE TITLE
Improvements to the diagram

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#8]
The current diagram describes 6 steps:
(1) Generate Attestation Key 
(2) Request  Client Key Attestation for generated key
(3) Generate Client Key Attestation
(4) Repond with Generated Client Key Attestation
(5) Generate Key Attestation PoP
(6) Interaction using Client Key Attestation + PoP for authentication

I would propose for:
(1) Generate key and client app attestations
(2) Request Client Attestation JWT
(3) Validate attestations and generate Client Attestation JWT
(4) Issue Client Attestation JWT
(5) Generate DPoP for Client Attestation JWT
(6) Authenticate using Client Attestation JWT + DPoP

**Comment by tplooker** [comment]
A couple of thoughts w.r.t this

Im not sure how much we want to talk about app attestations in this draft as it assumes the client instance is say a native app.

I think this issue has some good terminology suggestions WDYT about the following

Client Attestation JWT - Generated by the client backend
Client Instance PoP JWT - Generated by the client instance during client authentication (I dont think DPoP is right to use here w.r.t how it conflicts with DPoP)
Client Instance Key - What the client attestation jwt is bound to

**Comment by paulbastian** [comment]
Okay, is this covered by #11 ?
Ok to close for me
