### ISSUE TITLE
Replay attack prevention through AS contributed nonce

### ISSUE THREAD

**Issue by tplooker** [vcstuff/draft-ietf-oauth-attestation-based-client-auth#9]
Currently the specification does not define a mechanism for an AS contributed nonce to feature in the client attestation PoP meaning replay attack detection by authorisation servers requires tracking the JTI within the time window set by the PoP's iat claim. We should elaborate on an AS contributed nonce for the specification.

**Comment by tplooker** [comment]
I think this is an option, however the nonce for client authentication becomes dependent on the grant type which creates a bit of an awkward coupling when an application wants to say use client authentication for grant type other than pre auth code or authorisation code.

**Comment by tlodderstedt** [comment]
I think the flow can be used with and without nonce. 

If it is used without nonce, jti and short expiration must be used to limit the risk. 
If a nonce is used, I think using the codes is a pragmatic option. Alternatively, the AS could provide a dedicated nonce with the credential offer or authorization response. It could also provide the nonce with a token error response.

**Comment by paulbastian** [comment]
discussion on 23.05 is leaning towards DpoP-style error providing nonce

**Comment by tlodderstedt** [comment]
can we please bring this issue forward, it is very important?

> discussion on 23.05 is leaning towards DpoP-style error providing nonce

I see some advantages in that approach as it would allow the AS to request nonce use for all endpoints (including PAR).

**Comment by tlodderstedt** [comment]
on that topic, I would suggest such an AS provided nonce should be good up until the AS says otherwise. That would allow a client to use the same nonce for PAR and token endpoint.

**Comment by tplooker** [comment]
Update provided in #39

**Comment by paulbastian** [comment]
PR #49

**Comment by paulbastian** [comment]
PR #49
